from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 201)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_time = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(0, 10, 371, 41))
        self.label_time.setStyleSheet("font: 700 32pt \"Segoe UI\";")
        self.label_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.spin_box_hours = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spin_box_hours.setGeometry(QtCore.QRect(60, 100, 40, 31))
        self.spin_box_hours.setMaximum(24)
        self.spin_box_hours.setObjectName("spin_box_hours")
        self.spin_box_hours.setValue(1)
        self.button_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(70, 150, 75, 24))
        self.button_start.setObjectName("button_start")
        self.button_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(160, 150, 75, 24))
        self.button_stop.setObjectName("button_stop")
        self.button_stop.setEnabled(False)
        self.button_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(250, 150, 75, 24))
        self.button_exit.setObjectName("button_exit")
        self.combo_box_function = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_box_function.setGeometry(QtCore.QRect(10, 60, 331, 22))
        self.combo_box_function.setObjectName("combo_box_function")
        self.label_hours = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_hours.setGeometry(QtCore.QRect(20, 95, 49, 41))
        self.label_hours.setObjectName("label_hours")
        self.label_minutes = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_minutes.setGeometry(QtCore.QRect(110, 95, 49, 41))
        self.label_minutes.setObjectName("label_minutes")
        self.label_seconds = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_seconds.setGeometry(QtCore.QRect(210, 95, 49, 41))
        self.label_seconds.setObjectName("label_seconds")
        self.spin_box_minutes = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spin_box_minutes.setGeometry(QtCore.QRect(160, 100, 40, 31))
        self.spin_box_minutes.setMaximum(1000)
        self.spin_box_minutes.setObjectName("spin_box_minutes")
        self.spin_box_seconds = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spin_box_seconds.setGeometry(QtCore.QRect(270, 100, 40, 31))
        self.spin_box_seconds.setMaximum(1000)
        self.spin_box_seconds.setObjectName("spin_box_seconds")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 345, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.action_settings = QtGui.QAction(parent=MainWindow)
        self.action_settings.setObjectName("actionSettings")
        self.action_exit = QtGui.QAction(parent=MainWindow)
        self.action_exit.setObjectName("actionExit")
        self.action_autor = QtGui.QAction(parent=MainWindow)
        self.action_autor.setObjectName("actionAutor")
        self.action_about = QtGui.QAction(parent=MainWindow)
        self.action_about.setObjectName("actionAutor")
        #self.menuMenu.addAction(self.action_settings)
        self.menuMenu.addAction(self.action_exit)
        self.menuAbout.addAction(self.action_about)
        self.menuAbout.addAction(self.action_autor)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shutdown scheduler app"))
        self.label_time.setText(_translate("MainWindow", "01h:00m:00s"))
        self.button_start.setText(_translate("MainWindow", "START"))
        self.button_stop.setText(_translate("MainWindow", "STOP"))
        self.button_exit.setText(_translate("MainWindow", "EXIT"))
        self.label_hours.setText(_translate("MainWindow", "hours:"))
        self.label_minutes.setText(_translate("MainWindow", "minutes:"))
        self.label_seconds.setText(_translate("MainWindow", "seconds:"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.action_settings.setText(_translate("MainWindow", "Settings"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
        self.action_autor.setText(_translate("MainWindow", "Autor"))
        self.action_about.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
